Repository local-venture-group/Sugnee, pull requests merged in 2021-11, with the labels that each got.

#68 Feature/feature 67
  api/app/Http/Controllers/Api/User/Friku/FrikuFavoritesController.php
  api/app/Http/Controllers/Api/User/OwnedMaker/FavoritesController.php
  api/bootstrap/app.php
  api/env/.env.dev
  api/env/.env.example
  api/env/.env.prod
  api/env/.env.stg
  api/routes/api.php
  api/tests/Feature/FavoritesTest.php
Labels: マージok

#70 マイページからプロフィール画像アップロード
  web/friku/components/Button/index.stories.tsx
  web/friku/components/Button/index.tsx
  web/friku/components/Modal/CropModal/index.tsx
  web/friku/components/Profile/index.tsx
  web/friku/contexts/Auth/index.js
  web/friku/package-lock.json
  web/friku/package.json
  web/friku/pages/_app.tsx
  web/friku/pages/mypage/index.tsx
  web/friku/yarn.lock
Labels: レビュー待ち

#77 AuthUser型定義
  web/friku/contexts/Auth/index.tsx
Labels: マージok

#82 検索モーダルアラート解消 #75
  web/friku/components/Card/SearchTypeCard/index.tsx
  web/friku/components/Header/index.tsx
  web/friku/components/Modal/JobSearchModal/KeyWordTab/index.tsx
  web/friku/components/Modal/JobSearchModal/WorkLocationTab/index.tsx
  web/friku/components/Modal/JobSearchModal/WorkTypeTab/index.tsx
  web/friku/components/Modal/JobSearchModal/index.tsx
  web/friku/components/Modal/MobileSearchModal/index.tsx
  web/friku/pages/login/index.tsx
Labels: マージok

#84 updateProfileエラー解消 #83
  api/app/Http/Controllers/Api/User/UserController.php
  web/friku/components/Profile/index.tsx
  web/friku/contexts/Auth/index.tsx
Labels: マージok

#88 Feature/feature 81 change img upload s3
  api/app/Http/Controllers/Api/User/UserController.php
  api/app/Services/ImageService.php
  api/composer.json
  api/composer.lock
  api/config/app.php
  api/env/.env.dev
Labels: マージok, レビュー待ち

#94 Feature/feature 91 add name kana to signup
  web/friku/components/SignupConfirmation/user/index.tsx
  web/friku/components/SignupForm/user/index.tsx
  web/friku/contexts/Auth/index.tsx
  web/friku/interfaces/user.ts
  web/friku/pages/signup/index.tsx
  web/friku/pages/signup/success/index.tsx
Labels: マージok

#95 fixUserRegister
  api/app/Http/Controllers/Api/User/UserController.php
  api/app/Http/Requests/UserRequest.php
  web/friku/contexts/Auth/index.tsx
Labels: レビュー待ち

#96 Loadingコンポーネント作成
  web/sugnee/components/Loading/Loading.scss
  web/sugnee/components/Loading/index.tsx
  web/sugnee/package-lock.json
  web/sugnee/package.json
  web/sugnee/pages/_app.tsx
  web/sugnee/pages/contact/index.tsx
  web/sugnee/pages/pickup/[id]/index.tsx
  web/sugnee/pages/privacyPolicy/index.tsx
  web/sugnee/pages/terms/index.tsx
  web/sugnee/styles/Home.module.css
  web/sugnee/styles/components.scss
  web/sugnee/styles/globals.scss
  web/sugnee/yarn.lock
Labels: レビュー待ち

#97 Feature/feature 92 fix pickup show return data
  api/app/Http/Controllers/Api/User/Friku/FrikuJobsController.php
  api/database/migrations/2021_10_28_151722_create_friku_companies.php
  api/database/migrations/2021_11_26_180804_add_logo_address_sns_to_friku_companies_table.php
  api/database/seeders/FrikuCompaniesSeeder.php
  api/database/seeders/FrikuJoboffersSeeder.php
Labels: マージok

#99 フロントのDockerFileの修正
  docker-compose.yml
  web/Dockerfile
Labels: マージok

#103 add: apiの修正、注目記事系のテーブル追加、テストデータの投入, ディレクトリの移動
  api/app/Http/Controllers/Api/User/Friku/FrikuJobsController.php
  api/app/Http/Controllers/Api/User/JobSearchesController.php
  api/app/Http/Controllers/Api/User/OwnedMaker/JobsController.php
  api/app/Http/Controllers/Api/User/PagesController.php
  api/app/Models/FeaturedArticleContent.php
  api/app/Models/FeaturedCompanyArticle.php
  api/app/Models/FrikuCompany.php
  api/database/migrations/2021_11_29_132036_create_featured_company_articles_table.php
  api/database/migrations/2021_11_29_134836_create_featured_article_contents_table.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/FeaturedArticleContentsSeeder.php
  api/database/seeders/FeaturedCompanyArticlesSeeder.php
  api/routes/api.php
Labels: backend

#105 お気に入り追加済みか判定するロジック修正
  web/sugnee/components/Card/OmJobCard/index.tsx
  web/sugnee/pages/index.tsx
  web/sugnee/utils/index.ts
Labels: レビュー待ち

#113 Feature/feature 108 add apply frikujobs
  api/app/Http/Controllers/Api/User/UserController.php
  api/app/Models/FrikuApplicant.php
  api/app/Models/FrikuApplicantschedule.php
  api/app/Models/FrikuJoboffer.php
  api/app/Models/User.php
  api/database/factories/CorporationApplicantScheduleFactory.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/FavoritesSeeder.php
  api/database/seeders/FrikuFavoritesSeeder.php
Labels: マージok

#109 求人詳細~応募ページTS化
  api/app/Http/Controllers/Api/User/OwnedMaker/JobsController.php
  api/routes/api.php
  web/sugnee/contexts/Auth/index.tsx
  web/sugnee/pages/apply/[id].tsx
  web/sugnee/pages/apply/success/index.tsx
  web/sugnee/pages/job/[id]/index.tsx
  web/sugnee/pages/job/index.tsx
  web/sugnee/pages/pickup/[id]/index.tsx
Labels: レビュー待ち

#115 ページネーションコンポーネント作成
  web/sugnee/components/Pagination/index.tsx
  web/sugnee/pages/index.tsx
  web/sugnee/pages/pickup/[id]/index.tsx
  web/sugnee/pages/pickup/index.tsx
  web/sugnee/pages/pickup/page/[page].tsx
Labels: マージok
