Repository local-venture-group/Sugnee, pull requests merged in 2021-12, with the labels that each got.

#118 UserControllerのgetAuthUser, login , register後の返却ユーザー情報の修正
  api/app/Http/Controllers/Api/User/UserController.php
  api/app/Models/User.php
  api/app/Providers/UserServiceProvider.php
  api/app/Services/UserService.php
  api/config/app.php
Labels: マージok

#120 type_of_jobの付与　修正
  api/app/Http/Controllers/Api/User/Friku/FrikuJobsController.php
  api/app/Http/Controllers/Api/User/UserController.php
  api/app/Http/Resources/JobResource.php
  api/app/Models/FrikuJoboffer.php
  api/app/Services/UserService.php
  api/database/seeders/FrikuCompaniesSeeder.php
  api/database/seeders/FrikuJoboffersSeeder.php
Labels: マージok

#125 ユーザー情報にお気に入り＆応募済み求人追加
  web/sugnee/components/Footer/index.tsx
  web/sugnee/components/Header/index.tsx
  web/sugnee/components/Layout/index.tsx
  web/sugnee/components/MypageJobList/index.tsx
  web/sugnee/components/Profile/index.tsx
  web/sugnee/components/Seo/index.tsx
  web/sugnee/contexts/Auth/index.tsx
  web/sugnee/interfaces/job.ts
  web/sugnee/interfaces/user.ts
  web/sugnee/pages/apply/[id].tsx
  web/sugnee/pages/index.tsx
  web/sugnee/pages/mypage/index.tsx
Labels: レビュー待ち

#128 indexで入れてる求人カラムの名前文字列変換
  api/app/Http/Controllers/Api/User/UserController.php
  api/app/Http/Resources/JobResource.php
  api/app/Services/JobService.php
  api/app/Services/UserService.php
  web/sugnee/components/Card/OmJobCard/index.tsx
  web/sugnee/components/Card/PickupJobCard/index.tsx
  web/sugnee/pages/job/[id]/index.tsx
Labels: マージok

#131 404ページ作成
  web/sugnee/pages/404.tsx
Labels: レビュー待ち

#130 検索結果一覧ページ修正
  web/sugnee/components/JobSearchSidebar/index.tsx
  web/sugnee/components/Modal/JobSearchModal/index.tsx
  web/sugnee/components/Modal/MobileSearchModal/index.tsx
  web/sugnee/components/Pagination/Article/index.tsx
  web/sugnee/components/Pagination/JobOffer/index.tsx
  web/sugnee/contexts/Auth/index.tsx
  web/sugnee/contexts/SearchCondition/index.tsx
  web/sugnee/pages/job/index.tsx
  web/sugnee/pages/pickup/index.tsx
  web/sugnee/pages/pickup/page/[page].tsx
Labels: レビュー待ち, frontend

#129 ユーザーお気に入り、応募済みの求人に作成日付与
  api/app/Models/Favorite.php
  api/app/Models/User.php
  api/app/Services/UserService.php
  api/config/database.php
  api/database/factories/CorporationApplicantScheduleFactory.php
  api/database/factories/FrikuApplicantFactory.php
  api/database/factories/FrikuApplicantscheduleFactory.php
  api/database/migrations/2021_12_03_113901_drop_column_applied_at_column.php
  api/database/seeders/FavoritesSeeder.php
  api/database/seeders/FrikuFavoritesSeeder.php
Labels: レビュー待ち

#134 Admin，Staff型定義
  api/app/Http/Controllers/Api/Staff/StaffController.php
  api/routes/api.php
  web/sugnee/components/SignupConfirmation/staff/index.tsx
  web/sugnee/components/SignupForm/staff/index.tsx
  web/sugnee/contexts/Admin/index.tsx
  web/sugnee/contexts/Auth/index.tsx
  web/sugnee/contexts/Staff/index.tsx
  web/sugnee/interfaces/admin.ts
  web/sugnee/interfaces/staff.ts
  web/sugnee/pages/admin/index.jsx
  web/sugnee/pages/admin/index.tsx
  web/sugnee/pages/adminLogin/index.tsx
  web/sugnee/pages/staff/index.jsx
  web/sugnee/pages/staff/index.tsx
  web/sugnee/pages/staffLogin/index.tsx
  web/sugnee/pages/staffSignup/index.tsx
Labels: レビュー待ち, frontend

#139 Dockerfile修正&buildエラー解消
  .docker/api/Dockerfile
  .docker/web/Dockerfile
  docker-compose.yml
  web/Dockerfile
  web/sugnee/.env.production
  web/sugnee/components/Card/OmJobCard/index.tsx
  web/sugnee/components/Card/PickupJobCard/index.tsx
  web/sugnee/components/Modal/JobSearchModal/KeyWordTab/index.tsx
  web/sugnee/components/Modal/JobSearchModal/WorkLocationTab/index.tsx
  web/sugnee/components/Modal/JobSearchModal/WorkTypeTab/index.tsx
  web/sugnee/components/Modal/JobSearchModal/index.tsx
  web/sugnee/components/Modal/MobileSearchModal/index.tsx
  web/sugnee/components/SignupForm/staff/index.tsx
  web/sugnee/components/SignupForm/user/index.tsx
  web/sugnee/interfaces/job.ts
  web/sugnee/interfaces/user.ts
  web/sugnee/pages/job/index.tsx
  web/sugnee/pages/job/om/[id].tsx
  web/sugnee/pages/job/pickup/[id].tsx
  web/sugnee/pages/pickup/[id]/index.tsx
  web/sugnee/pages/pickup/index.tsx
  web/sugnee/pages/pickup/page/[page].tsx
  web/sugnee/pages/signup/index.tsx
  web/sugnee/pages/staffSignup/index.tsx
Labels: マージok

#141 addAllPickup & AllOm
  api/app/Http/Controllers/Api/User/Friku/FrikuJobsController.php
  api/app/Http/Controllers/Api/User/OwnedMaker/JobsController.php
  api/app/Models/FrikuJoboffer.php
  api/routes/api.php
Labels: マージok
